# Generated by Django 5.2.7 on 2025-10-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Number')),
                ('area', models.FloatField(verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Number floor')),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='houses/', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='houses/', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='houses/', verbose_name='Image 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='houses/', verbose_name='Image 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='houses/', verbose_name='Image 5')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
        ),
        migrations.CreateModel(
            name='HouseStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_house', models.CharField(max_length=100, verbose_name='Role in house')),
            ],
            options={
                'verbose_name': 'House staff',
                'verbose_name_plural': 'House staff',
            },
        ),
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Personal account number')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='Status')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Balance')),
            ],
            options={
                'verbose_name': 'Personal account',
                'verbose_name_plural': 'Personals accounts',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
    ]
