# Generated by Django 5.2.7 on 2025-10-20 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.tariff', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.floor', verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.house', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='housestaff',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.house', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='housestaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='house',
            name='staff',
            field=models.ManyToManyField(through='building.HouseStaff', to=settings.AUTH_USER_MODEL, verbose_name='Обслуживающий персонал'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='personal_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='building.personalaccount', verbose_name='Лицевой счет'),
        ),
        migrations.AddField(
            model_name='section',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='building.house', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='floor',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='building.section', verbose_name='Секция'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.section', verbose_name='Секция'),
        ),
        migrations.AlterUniqueTogether(
            name='housestaff',
            unique_together={('house', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('house', 'number')},
        ),
    ]
