# Generated by Django 5.2.7 on 2025-10-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='personal_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.personalaccount', verbose_name='Personal account'),
        ),
    ]
