# Generated by Django 5.2.7 on 2025-11-12 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Document', max_length=100, verbose_name='name')),
                ('document', models.FileField(upload_to='documents/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Name of Document',
                'verbose_name_plural': 'Name of Documents',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Gallery')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='SEO Title')),
                ('description', models.TextField(blank=True, verbose_name='SEO Description')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO Keywords')),
            ],
            options={
                'verbose_name': 'Seo Block',
                'verbose_name_plural': 'Seo Blocks',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/', verbose_name='Image')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.gallery', verbose_name='Gallery')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Slider title')),
                ('description', models.TextField(verbose_name='Slider description')),
                ('is_show_apps', models.BooleanField(default=True, verbose_name='is show apps')),
                ('gallery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.gallery', verbose_name='Slider Gallery')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.seoblock', verbose_name='SEO')),
            ],
            options={
                'verbose_name': 'home page',
                'verbose_name_plural': 'home pages',
            },
        ),
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_page/blocks/', verbose_name='Image')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='website.mainpage', verbose_name='home pages')),
            ],
            options={
                'verbose_name': 'Main block',
                'verbose_name_plural': 'Main blocks',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('fullname', models.CharField(blank=True, max_length=255, verbose_name='fullname')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('map', models.TextField(blank=True, verbose_name='map')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.seoblock', verbose_name='SEO')),
            ],
            options={
                'verbose_name': 'Contact page',
                'verbose_name_plural': 'Contact page',
            },
        ),
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=200, verbose_name='title 1')),
                ('description1', models.TextField(blank=True, verbose_name='description 1')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us/avatar', verbose_name='image')),
                ('title2', models.CharField(blank=True, max_length=200, verbose_name='title 2')),
                ('description2', models.TextField(blank=True, verbose_name='description 2')),
                ('gallery1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_us_gallery1', to='website.gallery', verbose_name='Gallery 1')),
                ('gallery2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_us_gallery2', to='website.gallery', verbose_name='Gallery 2')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.seoblock', verbose_name='SEO')),
            ],
            options={
                'verbose_name': 'About us page',
                'verbose_name_plural': 'About us pages',
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.seoblock', verbose_name='SEO')),
            ],
            options={
                'verbose_name': 'Service page',
                'verbose_name_plural': 'Service pages',
            },
        ),
        migrations.CreateModel(
            name='ServiceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/service_block', verbose_name='image')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='website.servicepage', verbose_name='Service page')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
