# Generated by Django 5.2.7 on 2025-11-12 13:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], max_length=10, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Revenue/expense item',
                'verbose_name_plural': 'Revenue/expense item',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('info', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Платежные реквизиты',
                'verbose_name_plural': 'Платежные реквизиты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Service')),
                ('show_in_counters', models.BooleanField(default=True, verbose_name='Show in counters')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tariff')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariffs',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='building.apartment', verbose_name='Квартира')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Счетчик',
                'verbose_name_plural': 'Счетчики',
            },
        ),
        migrations.CreateModel(
            name='CounterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='№')),
                ('date', models.DateField(verbose_name='Дата снятия')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Показание')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('considered', 'Учтено'), ('zero', 'Нулевое'), ('paid', 'Учтено и оплачено')], default='new', max_length=20, verbose_name='Статус')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='finance.counter', verbose_name='Счетчик')),
            ],
            options={
                'verbose_name': 'Показание счетчика',
                'verbose_name_plural': 'Показания счетчиков',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер квитанции')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Проведена')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Период с')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Период по')),
                ('status', models.CharField(choices=[('unpaid', 'Неоплачена'), ('partially_paid', 'Частично оплачена'), ('paid', 'Оплачена')], default='unpaid', max_length=20, verbose_name='Статус оплаты')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='building.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Квитанция',
                'verbose_name_plural': 'Квитанции',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction date')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.article', verbose_name='Article')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='building.personalaccount', verbose_name='personal account')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.receipt', verbose_name='receipt')),
            ],
            options={
                'verbose_name': 'Cash transaction',
                'verbose_name_plural': 'Cash transaction',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount charged')),
                ('consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='consumption')),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price per unit.')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.receipt', verbose_name='Receipt')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Receipt line',
                'verbose_name_plural': 'Receipts line',
                'unique_together': {('receipt', 'service')},
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='services',
            field=models.ManyToManyField(through='finance.ReceiptItem', to='finance.service', verbose_name='Услуги'),
        ),
        migrations.CreateModel(
            name='TariffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency', verbose_name='currency')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.service', verbose_name='Service')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tariff', verbose_name='Tariff')),
            ],
            options={
                'verbose_name': 'Service included in the tariff',
                'verbose_name_plural': 'Service included in the tariffs',
                'unique_together': {('tariff', 'service')},
            },
        ),
        migrations.AddField(
            model_name='tariff',
            name='services',
            field=models.ManyToManyField(through='finance.TariffService', to='finance.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.unit', verbose_name='Unit'),
        ),
    ]
