# Generated by Django 5.2.7 on 2025-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('info', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Платежные реквизиты',
                'verbose_name_plural': 'Платежные реквизиты',
            },
        ),
    ]
