# Generated by Django 5.2.7 on 2025-11-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_receipt_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.service', verbose_name='Service'),
        ),
    ]
