# Generated by Django 5.2.7 on 2025-11-17 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_tariffservice_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('template_file', models.FileField(upload_to='receipt_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='Файл шаблона (.xlsx)')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
            ],
            options={
                'verbose_name': 'Шаблон для печати',
                'verbose_name_plural': 'Шаблоны для печати',
            },
        ),
    ]
