# Generated by Django 5.2.7 on 2025-11-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_printtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Период c'),
        ),
    ]
