# Generated by Django 5.2.7 on 2025-11-25 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_initial'),
        ('finance', '0006_alter_receipt_period_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Кассовая операция', 'verbose_name_plural': 'Кассовые операции'},
        ),
        migrations.AddField(
            model_name='cashbox',
            name='is_posted',
            field=models.BooleanField(default=True, verbose_name='Проведен'),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ведомости'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='building.personalaccount', verbose_name='Лицевой счет'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.receipt', verbose_name='Квитанция'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата от'),
        ),
    ]
