# Generated by Django 5.2.7 on 2025-11-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_cashbox_options_cashbox_is_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер ведомости'),
        ),
    ]
