# Generated by Django 5.2.7 on 2025-10-23 14:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name role')),
                ('has_statistics', models.BooleanField(default=False, verbose_name='Access to statistics')),
                ('has_cashbox', models.BooleanField(default=False, verbose_name='Access to cashbox')),
                ('has_receipt', models.BooleanField(default=False, verbose_name='Access to receipt')),
                ('has_personal_account', models.BooleanField(default=False, verbose_name='Access to personal account')),
                ('has_apartment', models.BooleanField(default=False, verbose_name='Access to apartment')),
                ('has_owner', models.BooleanField(default=False, verbose_name='Access to owner')),
                ('has_house', models.BooleanField(default=False, verbose_name='Access to house')),
                ('has_message', models.BooleanField(default=False, verbose_name='Access to message')),
                ('has_ticket', models.BooleanField(default=False, verbose_name='Access to ticket')),
                ('has_counters', models.BooleanField(default=False, verbose_name='Access to counters')),
                ('has_management', models.BooleanField(default=False, verbose_name='Access to management site')),
                ('has_service', models.BooleanField(default=False, verbose_name='Access to service')),
                ('has_tariff', models.BooleanField(default=False, verbose_name='Access to tariff')),
                ('has_role', models.BooleanField(default=False, verbose_name='Access to role')),
                ('has_user', models.BooleanField(default=False, verbose_name='Access to user')),
                ('has_payment_details', models.BooleanField(default=False, verbose_name='Access to payment details')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique ID')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Middle name')),
                ('user_type', models.CharField(choices=[('employee', 'Сотрудник'), ('owner', 'Владелец')], default='owner', max_length=10, verbose_name='Type of user')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Отключен'), ('new', 'Новый')], default='new', max_length=10, verbose_name='Status')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profile image')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('viber', models.CharField(blank=True, max_length=20, verbose_name='Viber')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='Telegram')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.message', verbose_name='Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message recipient',
                'verbose_name_plural': 'Messages recipients',
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', through='users.MessageRecipient', to=settings.AUTH_USER_MODEL, verbose_name='Recipients'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'B работе'), ('done', 'Выполнено')], default='new', max_length=20, verbose_name='Status')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Time')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.apartment', verbose_name='Apartment')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role', verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User (author/master)')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
