# Generated by Django 5.2.7 on 2025-10-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID Владельца (ручной ввод)'),
        ),
    ]
