# Generated by Django 5.2.7 on 2025-11-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecipient',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
