# Generated by Django 5.2.7 on 2025-11-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owner_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID Владельца (ручной ввод)'),
        ),
    ]
