# Generated by Django 5.2.7 on 2025-11-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_messagerecipient_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecipient',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыто получателем'),
        ),
    ]
