# Generated by Django 5.2.7 on 2025-10-20 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Документ', max_length=100, verbose_name='Название документа для админки')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название галереи для админки')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='SEO Title')),
                ('description', models.TextField(blank=True, verbose_name='SEO Description')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO Keywords')),
            ],
            options={
                'verbose_name': 'SEO блок',
                'verbose_name_plural': 'SEO блоки',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/', verbose_name='Изображение')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок слайдера')),
                ('description', models.TextField(verbose_name='Описание слайдера')),
                ('is_show_apps', models.BooleanField(default=True, verbose_name='Показать ссылки на приложения')),
                ('gallery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gallery', verbose_name='Галерея для слайдера')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.seoblock', verbose_name='SEO блок')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_page/blocks/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок блока')),
                ('description', models.TextField(verbose_name='Описание блока')),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.mainpage', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Блок на главной',
                'verbose_name_plural': 'Блоки на главной',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, verbose_name='URL (например, ссылка на соцсеть)')),
                ('fullname', models.CharField(blank=True, max_length=255, verbose_name='ФИО / Название компании')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Город / Местоположение')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('map', models.TextField(blank=True, verbose_name='Код для вставки карты (HTML/JS)')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.seoblock', verbose_name='SEO блок')),
            ],
            options={
                'verbose_name': "Страница 'Контакты'",
                'verbose_name_plural': "Страница 'Контакты'",
            },
        ),
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200, verbose_name='Заголовок 1')),
                ('description1', models.TextField(verbose_name='Описание 1')),
                ('image', models.ImageField(upload_to='about_us/avatar', verbose_name='Изображение')),
                ('title2', models.CharField(max_length=200, verbose_name='Заголовок 2')),
                ('description2', models.TextField(verbose_name='Описание 2')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.document', verbose_name='Документ')),
                ('gallery1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_us_gallery1', to='core.gallery', verbose_name='Галерея 1')),
                ('gallery2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_us_gallery2', to='core.gallery', verbose_name='Галерея 2')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.seoblock', verbose_name='SEO блок')),
            ],
            options={
                'verbose_name': "Страница 'О нас'",
                'verbose_name_plural': "Страница 'О нас'",
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.seoblock', verbose_name='SEO блок')),
            ],
            options={
                'verbose_name': "Страница 'Услуги'",
                'verbose_name_plural': "Страница 'Услуги'",
            },
        ),
        migrations.CreateModel(
            name='ServiceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/service_block', verbose_name='Изображение услуги')),
                ('title', models.CharField(max_length=150, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicepage', verbose_name='Страница услуг')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
