# Generated by Django 5.2.7 on 2025-10-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='description1',
            field=models.TextField(blank=True, verbose_name='Описание 1'),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='description2',
            field=models.TextField(blank=True, verbose_name='Описание 2'),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/avatar', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='title1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок 1'),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='title2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок 2'),
        ),
    ]
